# --timestamp --db-dir /mnt/hdd/mynode/electrs --electrum-rpc-addr 0.0.0.0:50001 --jsonrpc-import --bulk-index-threads 3 --index-batch-size 12 --daemon-rpc-addr 127.0.0.1:8332 --txid-limit 100 --tx-cache-size-mb 10.0 --wait-duration-secs 15 

log_filters = "INFO"
#timestamp = true # Disabled, removed in later new electrs versions
#jsonrpc_import = true
jsonrpc_timeout_secs = 30
daemon_p2p_addr = "127.0.0.1:8334"  # Connect to bitcoin's whitebind port for unlimited download
daemon_rpc_addr = "127.0.0.1:8332"
db_dir = "/mnt/hdd/mynode/electrs"
electrum_rpc_addr = "0.0.0.0:50001"
monitoring_addr = "127.0.0.1:4224"
bulk_index_threads = 3
index_lookup_limit = 1000
tx_cache_size_mb = 10.0
wait_duration_secs = 15
network = "bitcoin"
